name: Sample Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Sample Workflow!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Running org level workflow
          echo This will run for every repo PR with azure-pipelines.yml
